// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbuezbtnwcydssokhmcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhidWV6YnRud2N5ZHNzb2tobWNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTE2ODcsImV4cCI6MjA2MjM4NzY4N30.hvbbI0zzj3w3cnBSrGBCGCclMZ3pIfZptUzpkxhROzA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);